language: node_js
node_js:
- '8'
sudo: required
services:
- docker
notifications:
  email: false
  slack:
    rooms:
      secure: IJY7ZbzyFjbYCRt+9URMDRTYteg4u0bc/SLqIm82FXJQhOhMh7JJO79EZH7ZGHZ5RsVKQss+ODEPKpF32reETMUzreP7rX27HXf/JFJrkwfA4ZZ7mQxVex4rQvpm9vWdmXV/VaLhoWTelBVX63z3JqEmG1AQSSVrxfSVf1igC+Zm/YGsXWhP1UuHLN+hOMEmn3UkFHXp3l1BlOuTXBNbYV4mmngAJ/AxbAoXvObGZQzZa+v0Cau/k/2lH1ycBRG31G8dmVwXmpjf90LZ5ew55uD1ZGjJ6bLPJZODa+gYFQjMPGwnpo40goOikyO1LXxarqvkHeVGkPEX2WtP7Vzwdp6aoBjiEfnU//7dvlEMdg/HrTfatfCP8JOiU6+ZmaNQ9MWFYCaLUGwr2AhB+3bL9kYJ+yaYQWXaxU7mhPd253SuRIH0lIEDIp5aY1O2kN9fbyLTkSPlslUpdfDSNLTCvIlus1EX2KMU6QyAKChVOFkuciiBaF6VZ6C+pvslH4ROv7cIVoC8nmaUfyoZds/GWhGybVfsgjgwizICBvsHGho9aeeO3djpYkf1FAGPKprS4z0OFl/1FCFDAJyxk32SXlyHWwDQYzZZzNClwrHiWpLCd7juWN4HY5YC8PV+QDeFdtYX/XQQxTHeIDXrKMBUjzDqd+2lJuEICo3IiJSyfkU=
    on_success: always
    on_failure: always
script:
- export VERSION=$(node -p -e "require('./package.json').version")
- docker build -t kalisio/k-seeder .
- docker tag kalisio/k-seeder kalisio/k-seeder:$VERSION
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
- docker push kalisio/k-seeder:$VERSION
